(define (square i) (* i i))
(define (sum-of-square x y) ( + (square x) (square y)) )
(define (sum-of-three a b c)
    (cond ((and (<= a b) (<= a c)) (sum-of-square b c))
        ((and (<= b a) (<= b c)) (sum-of-square a c))
        (else (sum-of-square a b))))
(sum-of-three 1 2 3)
(sum-of-three 1 1 1)
(sum-of-three 1 2 2)
(sum-of-three 1 1 2)
(sum-of-three 1 4 3)